# Generated by Django 6.1.1 on 2026-10-08 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainPage', '0003_solicitudcotizacion_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='GestionEstadoCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_REVISION', 'En revisión'), ('COTIZADA', 'Cotizada'), ('ACEPTADA', 'Aceptada'), ('RECHAZADA', 'Rechazada'), ('FINALIZADA', 'Finalizada')], default='PENDIENTE', max_length=20)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gestion_estados', to='mainPage.solicitudcotizacion')),
            ],
            options={
                'verbose_name': 'Gestión de estado de cotización',
                'verbose_name_plural': 'Gestión de estados de cotizaciones',
                'ordering': ['-fecha_cambio'],
            },
        ),
    ]
