# Generated by Django 6.1.1 on 2026-10-07 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudCotizacion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=150)),
                ('telefono', models.CharField(max_length=30)),
                ('tipo_solicitud', models.CharField(choices=[('INSTALACION_ELECTRICA', 'Instalación eléctrica'), ('PANELES_FOTOVOLTAICOS', 'Paneles fotovoltaicos'), ('MANTENCION_REPARACION', 'Mantención y reparación'), ('OTRO', 'Otro')], max_length=50)),
                ('descripcion', models.TextField()),
                ('ubicacion', models.CharField(max_length=250)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='solicitudes_cotizacion/')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Solicitud de cotización',
                'verbose_name_plural': 'Solicitudes de cotización',
                'db_table': 'solicitud_cotizacion',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
