# Generated by Django 6.1.1 on 2026-10-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0002_solicitudcotizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcotizacion',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_REVISION', 'En revisión'), ('COTIZADA', 'Cotizada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=20),
        ),
    ]
